### ISSUE TITLE
Explosions crash dedicated servers due to accessing ClientWorld

### ISSUE THREAD

**Issue by haykam821** [fabricservertools/HeyThatsMine#10]
The `ClientWorld` class is loaded by the `WorldEventListener` class. This fails on the dedicated server as the class does not exist in that environment.

https://github.com/fabricservertools/HeyThatsMine/blob/b572ce103e185b0e916b60b2f79b23daf33cc4d6/src/main/java/com/github/fabricservertools/htm/listeners/WorldEventListener.java#L63

**Comment by PotatoPresident** [comment]
Oops
